create table complaint (
   id int generated by default as identity primary key,
   product_id int not null,
   content varchar(1024) not null,
   complaintant varchar(50) not null,
   creation_timestamp timestamp with time zone not null,
   ip varchar(15),
   country varchar(2),
   counter int not null default 1
);
create unique index idx1 on complaint(complaintant, product_id);